// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB__qdg1t9LkzwWqVXWqnzVJ-CnSJpeCks',
    appId: '1:403010117366:web:1b26c2d3ac537f3f69d6d7',
    messagingSenderId: '403010117366',
    projectId: 'borrow-mii',
    authDomain: 'borrow-mii.firebaseapp.com',
    storageBucket: 'borrow-mii.firebasestorage.app',
    measurementId: 'G-QL43GTRREL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXV2z64oy-yHrmJbl8EiWBUmghLfE6WI',
    appId: '1:403010117366:android:ad2b50f75b97fdac69d6d7',
    messagingSenderId: '403010117366',
    projectId: 'borrow-mii',
    storageBucket: 'borrow-mii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBsrr7IX-SQoGPBrPBZtCI-ihOHOx_r8',
    appId: '1:403010117366:ios:524eb4ffe2ca057069d6d7',
    messagingSenderId: '403010117366',
    projectId: 'borrow-mii',
    storageBucket: 'borrow-mii.firebasestorage.app',
    androidClientId: '403010117366-mrl6uvcgjov9t8599ip5natuupudut9v.apps.googleusercontent.com',
    iosClientId: '403010117366-pefh06jficmtrhi669ndubvdfejies5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamDProject',
  );

}