// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9nDJZ0B5pYobVeiStYegKMNRH18wPOQ',
    appId: '1:840944533353:web:3589d6ae5760fb402487f8',
    messagingSenderId: '840944533353',
    projectId: 'borrowmii-53cc9',
    authDomain: 'borrowmii-53cc9.firebaseapp.com',
    storageBucket: 'borrowmii-53cc9.appspot.com',
    measurementId: 'G-RVM7PTSTB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49HQQL9nUG4jDadzQlewrtXMDE6zNle8',
    appId: '1:840944533353:android:f5afb447e6e7b5c12487f8',
    messagingSenderId: '840944533353',
    projectId: 'borrowmii-53cc9',
    storageBucket: 'borrowmii-53cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYfE9cQA6WYuAqYudRr-MjfWC0h-1yvAg',
    appId: '1:840944533353:ios:8d5afc5c8cc632f52487f8',
    messagingSenderId: '840944533353',
    projectId: 'borrowmii-53cc9',
    storageBucket: 'borrowmii-53cc9.appspot.com',
    iosClientId:
        '840944533353-b1ifn5cefqa20o5to4cuokp9bu0v332v.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamDProject',
  );
}
